sudo: required
dist: trusty
language: cpp
compiler: 
g++:
    - 4.9
    - 5.0
    - 5.4.0
    - trunk
stdlib:
  - libc++
  - stdlibc++
std:
  - c++03
  - c++11
  - c++14
install: export CXX="g++-5"
os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install g++-5
    - cd ./test/
script: make
