sudo: required
dist: trusty
language: cpp
compiler: 
g++:
    - 4.9
    - 5.0
    - 5.4.0
    - trunk
stdlib:
  - libc++
  - stdlibc++
std:
  - c++03
  - c++11
  - c++14
install: export CXX="g++-5"
os: linux
addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - g++-5-multilib
            - libc6-dev
            - libx11-dev

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libc6-dev
    - sudo apt-get install gcc-5-multilib
    - sudo apt-get install gcc-6-base
    - sudo apt-get install g++-5-multilib
    - sudo apt-get install g++-5
    - cd ./test/
script: make
